version: "2.0"

services:
  vscode:
    container_name: vscode
    image: alexandreoda/vscode
    restart: "no"
    network_mode: host
    privileged: false
    cap_add:
      - SYS_ADMIN
    environment:
      - DISPLAY
    volumes:
      - "${HOME}:/home/vscode"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/tmp/.X11-unix:/tmp/.X11-unix"